
target 'MentalSnapp' do

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.7'
pod 'SVPullToRefresh'
pod "MagicalRecord"
pod 'ALAlertBanner', '~>0.3.1'
pod 'GoogleAnalytics'
pod 'Google/Analytics'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'

pod 'DateTools'
pod 'JSONModel'
pod 'JTProgressHUD'

pod 'AWSCore'
pod 'AWSS3'

end



